version: 2.1
orbs:
  matlab: mathworks/matlab@1
jobs:
  run-matlab-tests:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          # select-by-name: $(circleci tests glob "tests/**/*.m" | awk -F'[\\\\/.]' '{print $(NF-1)}' | sort | uniq | circleci tests split --split-by=timings | awk '{print $0 "/*"}')
          source-folder: src
          test-results-junit: test-results/results.xml
          
      - run:
          command: cat test-results/results.xml
            
      - store_test_results:
          path: test-results/results.xml 
workflows:
  test:
    jobs:
      - run-matlab-tests:
          context: my-context